// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticalWork.Library.Data.PostgreSql;

#nullable disable

namespace PracticalWork.Library.Data.PostgreSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512212026_FixBookInheritanceMapping")]
    partial class FixBookInheritanceMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Authors")
                        .HasColumnType("text[]");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("book_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("books", (string)null);

                    b.HasDiscriminator<string>("book_type").HasValue("base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.BookBorrowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AbstractBookEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BorrowDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ReaderEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AbstractBookEntityId");

                    b.HasIndex("ReaderEntityId");

                    b.ToTable("book_borrows", (string)null);
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.NotificationLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowId")
                        .HasColumnType("uuid")
                        .HasColumnName("borrow_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.ReaderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("readers", (string)null);
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.EducationalBookEntity", b =>
                {
                    b.HasBaseType("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity");

                    b.Property<string>("GradeLevel")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.ToTable("books");

                    b.HasDiscriminator().HasValue("educational");
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.FictionBookEntity", b =>
                {
                    b.HasBaseType("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity");

                    b.Property<string>("CategoriesOfFiction")
                        .HasColumnType("text");

                    b.ToTable("books");

                    b.HasDiscriminator().HasValue("fiction");
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.ScientificBookEntity", b =>
                {
                    b.HasBaseType("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<string>("ResearchField")
                        .HasColumnType("text");

                    b.ToTable("books");

                    b.HasDiscriminator().HasValue("scientific");
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.BookBorrowEntity", b =>
                {
                    b.HasOne("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity", null)
                        .WithMany("IssuanceRecords")
                        .HasForeignKey("AbstractBookEntityId");

                    b.HasOne("PracticalWork.Library.Data.PostgreSql.Entities.ReaderEntity", null)
                        .WithMany("BorrowedRecords")
                        .HasForeignKey("ReaderEntityId");
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.AbstractBookEntity", b =>
                {
                    b.Navigation("IssuanceRecords");
                });

            modelBuilder.Entity("PracticalWork.Library.Data.PostgreSql.Entities.ReaderEntity", b =>
                {
                    b.Navigation("BorrowedRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
